name: CI - Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: xdebug

      - name: Instalar dependências
        run: composer i --no-ansi --no-interaction --no-suggest --prefer-dist --optimize-autoloader

      - name: Gerar chave Laravel
        run: php artisan key:generate

      - name: Rodar testes
        run: ./vendor/bin/pest
